Models/ClassModel.cs
using System;

namespace TowerHallSimulator.Models
{
    public class ClassModel
    {
        int id;
        string name;
        string professor;
        int studentNum;
        int roomNum;
        string classTime;

        public ClassModel(int id, string name, string professor, int studentNum, int roomNum, string classTime)
        {
            this.id = id;
            this.name = name;
            this.professor = professor;
            this.studentNum = studentNum;
            this.roomNum = roomNum;
            this.classTime = classTime;
        }

        public int Id { get => id; set => id = value; }
        public string Name { get => name; set => name = value; }
        public string Professor { get => professor; set => professor = value; }
        public int StudentNum { get => studentNum; set => studentNum = value; }
        public int RoomNum { get => roomNum; set => roomNum = value; }
        public string ClassTime { get => classTime; set => classTime = value; }
    }
}

Models/ClassRepository.cs
using System;
using System.Collections.Generic;

namespace TowerHallSimulator.Models
{
    public class ClassRepository
    {
        List<ClassModel> towerClasses = new List<ClassModel>();
        public ClassRepository()
        {
            towerClasses.Add(new ClassModel(0, "Placeholder", "Professor", 20, 100, "8:00"));
            towerClasses.Add(new ClassModel(1, "Placeholder", "Professor", 20, 100, "8:00"));
            towerClasses.Add(new ClassModel(2, "Placeholder", "Professor", 20, 100, "8:00"));
        }

        public List<ClassModel> getAllClasses()
        {
            return (towerClasses);
        }

        public ClassModel getOneClass(int index)
        {
            return (towerClasses[index]);
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace TowerHallSimulator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/FifthFloorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TowerHallSimulator.Models;

namespace TowerHallSimulator.Controllers
{
    public class FifthFloorController : Controller
    {
        public IActionResult Double()
        {
            return View();
        }
        public IActionResult Single()
        {
            return View();
        }
    }
}

Controllers/FirstFloorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TowerHallSimulator.Models;

namespace TowerHallSimulator.Controllers
{
    public class FirstFloorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FourthFloorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TowerHallSimulator.Models;

namespace TowerHallSimulator.Controllers
{
    public class FourthFloorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GroundFloorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TowerHallSimulator.Models;

namespace TowerHallSimulator.Controllers
{
    public class GroundFloorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HelloController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TowerHallSimulator.Models;

namespace TowerHallSimulator.Controllers
{
    public class HelloController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Minnesota()
        {
            return View();
        }
        public IActionResult Wisconsin()
        {
            return View();
        }
        public IActionResult Maryland()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TowerHallSimulator.Models;

namespace TowerHallSimulator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return base.View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SecondFloorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TowerHallSimulator.Models;

namespace TowerHallSimulator.Controllers
{
    public class SecondFloorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ThirdFloorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TowerHallSimulator.Models;

namespace TowerHallSimulator.Controllers
{
    public class ThirdFloorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/FifthFloor/Double.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>
    This floor is under construction. Please be patient as we build up the program.
</p>

Views/FifthFloor/Maryland.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Welcome to Maryland!</h1>
<br>
<h3>Population</h3>
<p>In 2020, the population of Minnesota was 6.038 million people.</p>

Views/FifthFloor/Single.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>
    This floor is under construction. Please be patient as we build up the program.
</p>

Views/FifthFloor/Wisconsin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Welcome to Wisconsin!</h1>
<br>
<h3>Population</h3>
<p>In 2020, the population of Wisconsin was 5.807 million people!</p>

Views/First Floor/Index.cshtml
@model IEnumerable<TowerHallSimulator.Models.StudentModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Credits)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/FirstFloor/Index.cshtml
<h1>Tower Hall, First Floor</h1>
<!--flavortext at the top of the page-->
<p>
    This floor has no classrooms. <br>
    In the main hallway, there are displays for each of the Benedictine Values, along with other values of the College.
</p>
<h2>Unique Rooms</h2>
<p>
    The unique areas on this floor include Mitchell Auditorium, the IT Service Desk, the Center for Experiential Learning, and the Saints Shop.
</p>
<!---calling methods-->
@{<!--special features of the floor-->
    <!--instantiating objects-->
    Auditorium mitchell = new Auditorium();
    ITServiceDesk desk = new ITServiceDesk();
    ExperientialLearning center = new ExperientialLearning();
    SaintsShop shop = new SaintsShop();
    <!--printing HTML-->
    @Html.Raw(mitchell.Mitchell());
    <br>
    @Html.Raw(desk.Desk());
    <br>
    @Html.Raw(center.Center());
    <br>
    @Html.Raw(shop.Shop());
    <br>
    <br>
}

Views/FourthFloor/Index.cshtml
<h1>Tower Hall, Fourth Floor</h1>
<!--flavortext at the top of the page-->
<p>
    This floor houses the School of Arts and Letters. <br>
    Several paintings line the walls; some of them were created by students. <br>
    You also see newsboards for the individual departments on this floor.
</p>
<h2>Unique Rooms</h2>
<p>
    The unique rooms on this floor include the photography darkroom, honors lounge, music library, and music practice rooms.
</p>
<!---calling methods-->
@{<!--special features of the floor-->
    <!--instantiating objects-->
    PhotographyDarkoom darkroom = new PhotographyDarkoom();
    HonorsLounge lounge = new HonorsLounge();
    MusicLibrary library = new MusicLibrary();
    MusicPracticeRooms practice = new MusicPracticeRooms();
    <!--printing HTML-->
    @Html.Raw(darkroom.Darkroom());
    <br>
    @Html.Raw(lounge.Lounge());
    <br>
    @Html.Raw(library.Library());
    <br>
    @Html.Raw(practice.PracticeRooms());
    <br>
    <br>
}
<h2>Classrooms</h2>
@{<!--classrooms; since the contents are random each time, I only need one object for each class-->
    <!--instantiating objects-->
    Activity classroomActivity = new Activity();
    Analogy classroomAnalogy = new Analogy();
    Attendance classroomAttendance = new Attendance();
    Reaction classroomReaction = new Reaction();

    <!---brackets for ease of containing the HTML methods for each classroom-->
    <!--the same methods are called over and over, but I'm not sure how to put the calls into a single method if I'm in a cshtml file.-->
    <span>Classroom 4414</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 4605</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 4611</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 4105</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 4115</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 4119</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 4125</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 4141</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
}

<!--
<a asp-action="double" asp-controller="FifthFloor">Double Classroom</a>
<br>
<a asp-action="single" asp-controller="FifthFloor">Single Conference Room</a>
<br>
--->

Views/GroundFloor/Index.cshtml
<h1>Tower Hall, Ground Floor</h1>
<!--flavortext at the top of the page-->
<p>
    This floor has no classrooms. <br>
    The area is pretty open, with posters plastered all over the walls for events and groups on campus.
</p>
<h2>Unique Rooms</h2>
<p>
    The unique areas on this floor include Storm's Den, the Mailroom, the Intercultural Center, and the Oratory.
</p>
<!---calling methods-->
@{<!--special features of the floor-->
    <!--instantiating objects-->
    StormsDen storms = new StormsDen();
    Mailroom mailroom = new Mailroom();
    InterculturalCenter center = new InterculturalCenter();
    Oratory oratory = new Oratory();
    <!--printing HTML-->
    @Html.Raw(storms.Den());
    <br>
    @Html.Raw(mailroom.Mail());
    <br>
    @Html.Raw(center.Center());
    <br>
    @Html.Raw(oratory.Room());
    <br>
    <br>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h6>Software Design, CIS 3285 500, Fall 2022</h6>
    <p>created by Veronica Poquette</p>
    <br>
    <p>
        This program provides a fun simulator of walking through Tower Hall as classes are in session. <br>
        You can use the different tabs to "walk" on different floors.
    </p>
</div>

Views/SecondFloor/Index.cshtml
<h1>Tower Hall, Second Floor</h1>
<!--flavortext at the top of the page-->
<p>
    Several works of art line the walls. <br>
    There's also some boards with tips and tricks for success in the main hallway, <br>
    as well as details on academic programs.
</p>
<h2>Unique Rooms</h2>
<p>
    There are a number of unique rooms on this floor, including the Writing Center, Veterans Center, Tutoring Center, <br>
    micro lab, Facilities area, Counseling offices, and McNair Scholar Center.
</p>
<!---calling methods-->
@{ <!--special features of the floor-->
    <!--instantiating objects-->
    WritingCenter writing = new WritingCenter();
    VeteransCenter veterans = new VeteransCenter();
    TutoringCenter tutoring = new TutoringCenter();
    MicroLab lab = new MicroLab();
    Facilities facilities = new Facilities();
    Counseling counseling = new Counseling();
    McNair mcNair = new McNair();

    <!--printing HTML-->
    @Html.Raw(writing.Center());
    <br>
    @Html.Raw(veterans.Center());
    <br>
    @Html.Raw(tutoring.Center());
    <br>
    @Html.Raw(lab.Lab());
    <br>
    @Html.Raw(facilities.FacilitiesArea());
    <br>
    @Html.Raw(counseling.Counsel());
    <br>
    @Html.Raw(mcNair.Center());
    <br>
    <br>
}
<h2>Classrooms</h2>
@{ <!--classrooms-->
    <!--instantiating objects-->
    Activity classroomActivity = new Activity();
    Analogy classroomAnalogy = new Analogy();
    Attendance classroomAttendance = new Attendance();
    Reaction classroomReaction = new Reaction();

    <!---brackets for ease of containing the HTML methods for each classroom-->
    <!--the same methods are called over and over, but I'm not sure how to put the calls into a single method if I'm in a cshtml file.-->
    <span>Classroom 2607  </span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 2611</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 2420</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 2412</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 2121A</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TowerHallSimulator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<style>
    body{
        background-color: deepskyblue;
    }
</style>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tower Hall Simulator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GroundFloor" asp-action="Index">Ground Floor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FirstFloor" asp-action="Index">First Floor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SecondFloor" asp-action="Index">Second Floor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ThirdFloor" asp-action="Index">Third Floor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FourthFloor" asp-action="Index">Fourth Floor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Tower Hall Simulator Poquette - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/ThirdFloor/Index.cshtml
<h1>Tower Hall, Third Floor</h1>
<!--flavortext at the top of the page-->
<p>
    This floor houses the School of Business, Leadership, and Professional Studies. <br>
    In the main hallway, there are boards of alumni success stories and display boards of faculty.
</p>
<h2>Unique Rooms</h2>
<p>
    The unique rooms on this floor include the music hall and the Native Student Center.
</p>
<!---calling methods-->
@{<!--special features of the floor-->
    <!--instantiating objects-->
    MusicHall hall = new MusicHall();
    NativeStudentCenter center = new NativeStudentCenter();
    <!--printing HTML-->
    @Html.Raw(hall.Hall());
    <br>
    @Html.Raw(center.Center());
    <br>
    <br>
}
<h2>Classrooms</h2>
@{<!--classrooms; since the contents are random each time, I only need one object for each class-->
    <!--instantiating objects-->
    Activity classroomActivity = new Activity();
    Analogy classroomAnalogy = new Analogy();
    Attendance classroomAttendance = new Attendance();
    Reaction classroomReaction = new Reaction();

    <!---brackets for ease of containing the HTML methods for each classroom-->
    <!--the same methods are called over and over, but I'm not sure how to put the calls into a single method if I'm in a cshtml file.-->
    <span>Classroom 3414</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 3410</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 3615</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 3121</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 3131</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 3141</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 3147</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
    <span>Classroom 3150</span>
    {
        <br>
        @Html.Raw(classroomActivity.SpecialActivity());
        <br>
        @Html.Raw(classroomAttendance.RandomAttendance());
        <br>
        @Html.Raw(classroomAnalogy.RandomAnalogy());
        <br>
        @Html.Raw(classroomReaction.RandomReaction());
        <br>
    }
    <br>
}